# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Things3 < Formula
  desc "CLI for Things 3 task manager on macOS"
  homepage "https://github.com/moonD4rk/things3"
  version "0.5.2"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/moonD4rk/things3/releases/download/v0.5.2/things3_macos_intel.tar.gz"
    sha256 "b1b982c5b489ffa32f8480554b05cd56955903d5d65e346133ea2bef4aeb7084"

    def install
      bin.install "things3"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/moonD4rk/things3/releases/download/v0.5.2/things3_macos_m1.tar.gz"
    sha256 "14eaa3151512b2d863aa7893efe43eb09632a426e0984b519f998a9e21002543"

    def install
      bin.install "things3"
    end
  end

  def caveats
    <<~EOS
      things3 requires read access to the Things 3 database.
      Make sure Things 3 is installed on your Mac.
    EOS
  end

  test do
    system "#{bin}/things3", "version"
  end
end
