# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccstatus < Formula
  desc "A customizable status line formatter for Claude Code CLI"
  homepage "https://github.com/moonD4rk/ccstatus"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moonD4rk/ccstatus/releases/download/v0.1.1/ccstatus_darwin_x86_64.tar.gz"
      sha256 "a6440488759d3ca5399fe874d01f0c244cab8b91acc0b86bc745af666ecee237"

      define_method(:install) do
        bin.install "ccstatus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moonD4rk/ccstatus/releases/download/v0.1.1/ccstatus_darwin_arm64.tar.gz"
      sha256 "6aaf7dfe7c3f834243d436aae477d74d0af48986c672a06d9b31235bec17278e"

      define_method(:install) do
        bin.install "ccstatus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonD4rk/ccstatus/releases/download/v0.1.1/ccstatus_linux_x86_64.tar.gz"
      sha256 "5208c2bab9746592affb2379d8c2c5768840b0cd78483bf3716fb052828dfe54"
      define_method(:install) do
        bin.install "ccstatus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonD4rk/ccstatus/releases/download/v0.1.1/ccstatus_linux_arm64.tar.gz"
      sha256 "10c387489eb85b91221113f38b1deb9ac06941fa0d0c174bc044fe3d799fcbb7"
      define_method(:install) do
        bin.install "ccstatus"
      end
    end
  end

  test do
    system "#{bin}/ccstatus", "--version"
  end
end
