# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccstatus < Formula
  desc "Customizable status line formatter for Claude Code CLI"
  homepage "https://github.com/moonD4rk/ccstatus"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moonD4rk/ccstatus/releases/download/v0.1.3/ccstatus_darwin_x86_64.tar.gz"
      sha256 "61edcc32d65fc7a9411968a1f7713555557bf674f048786ea361e9120de8b95a"

      define_method(:install) do
        bin.install "ccstatus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moonD4rk/ccstatus/releases/download/v0.1.3/ccstatus_darwin_arm64.tar.gz"
      sha256 "0f10c9ec4cf01cc76f23bf106670bc2b33d568a7329ac47338307d4432fc32e8"

      define_method(:install) do
        bin.install "ccstatus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonD4rk/ccstatus/releases/download/v0.1.3/ccstatus_linux_x86_64.tar.gz"
      sha256 "28051aa5dbd782cc1661488adfa6e09b79a62342c023b858f2ae9014c0f1992f"
      define_method(:install) do
        bin.install "ccstatus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonD4rk/ccstatus/releases/download/v0.1.3/ccstatus_linux_arm64.tar.gz"
      sha256 "0e7802008c5b3cb16719533f55e65b859693dfed13977360ba805ea48833f315"
      define_method(:install) do
        bin.install "ccstatus"
      end
    end
  end

  test do
    system "#{bin}/ccstatus", "--version"
  end
end
