# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HackBrowserData < Formula
  desc "Extract and decrypt browser data from multiple browsers"
  homepage "https://github.com/moonD4rk/HackBrowserData"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moonD4rk/HackBrowserData/releases/download/v0.5.0/hack-browser-data-osx-64bit.tar.gz"
      sha256 "95ddefab956e8c764f4bb093b25d47e3b39bac76215385b36fd393d075b30bd2"

      define_method(:install) do
        bin.install "hack-browser-data"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moonD4rk/HackBrowserData/releases/download/v0.5.0/hack-browser-data-osx-arm64.tar.gz"
      sha256 "41cf4c33f5079d292448c6fc8bfe768bab3341cfb19d89247293d05065ae711b"

      define_method(:install) do
        bin.install "hack-browser-data"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonD4rk/HackBrowserData/releases/download/v0.5.0/hack-browser-data-linux-64bit.tar.gz"
      sha256 "8ebbbe62710f3fc6c65b53fdf73e82e191331eb5a121acb0d25ecfd044e2e6b2"
      define_method(:install) do
        bin.install "hack-browser-data"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/moonD4rk/HackBrowserData/releases/download/v0.5.0/hack-browser-data-linux-arm.tar.gz"
      sha256 "be2eb20d1ab127712771a1afc744a303999a76f34bf52ba6335052f1b2467025"
      define_method(:install) do
        bin.install "hack-browser-data"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonD4rk/HackBrowserData/releases/download/v0.5.0/hack-browser-data-linux-arm64.tar.gz"
      sha256 "310b0fb12725e45e1c35cfc85d561ec9a485cb1a01aef54b5b4013eba7677021"
      define_method(:install) do
        bin.install "hack-browser-data"
      end
    end
  end

  test do
    system "#{bin}/hack-browser-data", "version"
  end
end
