# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keychainbreaker < Formula
  desc "Extract credentials from macOS Keychain files"
  homepage "https://github.com/moonD4rk/keychainbreaker"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moonD4rk/keychainbreaker/releases/download/v0.2.2/keychainbreaker_darwin_amd64.tar.gz"
      sha256 "4102098f80bff053ca74ae6f8e3c3435f4c2133869b7448046b4cc2645808f1c"

      define_method(:install) do
        bin.install "keychainbreaker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moonD4rk/keychainbreaker/releases/download/v0.2.2/keychainbreaker_darwin_arm64.tar.gz"
      sha256 "25cfcd3d815b8b8c6ff160bc75b4c67656f892d42ec777afd4d938fd9c84320f"

      define_method(:install) do
        bin.install "keychainbreaker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonD4rk/keychainbreaker/releases/download/v0.2.2/keychainbreaker_linux_amd64.tar.gz"
      sha256 "4422b131e6bbd86d01a7c9ab900a9050b3c1c710a43c7b8dd5873160638bfcfc"
      define_method(:install) do
        bin.install "keychainbreaker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonD4rk/keychainbreaker/releases/download/v0.2.2/keychainbreaker_linux_arm64.tar.gz"
      sha256 "61bc5c26eaa73d7ba40802277e3be00215738915f2c006976fac326448985f8f"
      define_method(:install) do
        bin.install "keychainbreaker"
      end
    end
  end

  def caveats
    <<~EOS
      keychainbreaker reads macOS Keychain files (login.keychain-db).
      The keychain file must be accessible to extract credentials.
    EOS
  end

  test do
    system "#{bin}/keychainbreaker", "version"
  end
end
