# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keychainbreaker < Formula
  desc "Extract credentials from macOS Keychain files"
  homepage "https://github.com/moonD4rk/keychainbreaker"
  version "0.2.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moonD4rk/keychainbreaker/releases/download/v0.2.6/keychainbreaker_darwin_amd64.tar.gz"
      sha256 "c00c2606978ce15a7d2137558c6f2ce3c12035c84f54d71ab7cb8108a77456e2"

      define_method(:install) do
        bin.install "keychainbreaker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moonD4rk/keychainbreaker/releases/download/v0.2.6/keychainbreaker_darwin_arm64.tar.gz"
      sha256 "4081aa0952c54ef9bc55b0a06cc7b2a55b201aa81dd41a7185a3dce034e46f2b"

      define_method(:install) do
        bin.install "keychainbreaker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonD4rk/keychainbreaker/releases/download/v0.2.6/keychainbreaker_linux_amd64.tar.gz"
      sha256 "b3b0c2c2d59ec0e75e1888cfdfce566a6d40eeacf43f1a43df61685300980577"
      define_method(:install) do
        bin.install "keychainbreaker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonD4rk/keychainbreaker/releases/download/v0.2.6/keychainbreaker_linux_arm64.tar.gz"
      sha256 "a53902ec17a61539d07b0c8393214973b836b8195e6bdfa443d64f41067a204d"
      define_method(:install) do
        bin.install "keychainbreaker"
      end
    end
  end

  def caveats
    <<~EOS
      keychainbreaker reads macOS Keychain files (login.keychain-db).
      The keychain file must be accessible to extract credentials.
    EOS
  end

  test do
    system "#{bin}/keychainbreaker", "version"
  end
end
