# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Things3 < Formula
  desc "CLI for Things 3 task manager on macOS"
  homepage "https://github.com/moonD4rk/things3"
  version "0.5.5"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/moonD4rk/things3/releases/download/v0.5.5/things3_macos_intel.tar.gz"
    sha256 "f10f4f359d4186cc7ceb05004a822ad4b25f8050ebd90df981bbc4fb53d2dbc3"

    define_method(:install) do
      bin.install "things3"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/moonD4rk/things3/releases/download/v0.5.5/things3_macos_m1.tar.gz"
    sha256 "6c2aae71ff7f28e9bb1766311eb9d3ff8e3c0a85ed9c6a9ca46c92c710266772"

    define_method(:install) do
      bin.install "things3"
    end
  end

  def caveats
    <<~EOS
      things3 requires read access to the Things 3 database.
      Make sure Things 3 is installed on your Mac.
    EOS
  end

  test do
    system "#{bin}/things3", "version"
  end
end
